on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 - name: Set up JDK 21
  uses: actions/setup-java@v3
  with:
    distribution: 'temurin'
    java-version: '21'
- name: Submit dependencies
  uses: gradle/dependency-submission-action@v2
- name: Set up Gradle
  uses: gradle/actions/setup-gradle@v3
  with:
    gradle-version: '8.10'
- name: Run tests with Gradle
  run: gradle test

- name: Upload test report
  uses: actions/upload-artifact@v3
  with:
    name: Test Reports
    path: build/reports/tests/
