name: pmd

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read  # Permet à GitHub Actions de lire le contenu du dépôt

jobs:
  pmd-code-scan:
    permissions:
      contents: read  # Nécessaire pour récupérer le code via actions/checkout
      security-events: write  # Permet d'uploader les résultats SARIF dans GitHub
      actions: read  # Nécessaire si tu utilises des actions privées

    runs-on: ubuntu-latest  # L'environnement d'exécution pour les jobs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Récupère le code source de ton dépôt

      - name: Set up JDK 21
        uses: actions/setup-java@v4  # Installe et configure JDK 21
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run PMD Analysis
        id: pmd
        uses: pmd/pmd-github-action@v2  # Utilisation de l'action GitHub officielle pour PMD
        with:
          rulesets: 'rulesets/java/quickstart.xml'  # Définit les règles à utiliser pour l'analyse
          sourcePath: 'src/main/java'  # Chemin vers ton code source
          analyzeModifiedFilesOnly: false  # Analyse tous les fichiers, pas seulement ceux modifiés

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3  # Upload des résultats SARIF vers GitHub
        with:
          sarif_file: pmd-report.sarif  # Le fichier SARIF généré par l'analyse PMD
